/* Generated By:JavaCC: Do not edit this line. DTLConstants.java */
package breder.dtl.el.parse;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface DTLConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int SINGLE_LINE_COMMENT = 6;
	/** RegularExpression Id. */
	int JAVA_DOC_COMMENT = 9;
	/** RegularExpression Id. */
	int MULTI_LINE_COMMENT = 10;
	/** RegularExpression Id. */
	int PLUS = 12;
	/** RegularExpression Id. */
	int MINUS = 13;
	/** RegularExpression Id. */
	int MULTIPLY = 14;
	/** RegularExpression Id. */
	int DIVIDE = 15;
	/** RegularExpression Id. */
	int EQUAL = 16;
	/** RegularExpression Id. */
	int NOT = 17;
	/** RegularExpression Id. */
	int GREATER = 18;
	/** RegularExpression Id. */
	int LOWER = 19;
	/** RegularExpression Id. */
	int DOT = 20;
	/** RegularExpression Id. */
	int COMMA = 21;
	/** RegularExpression Id. */
	int LPARAM = 22;
	/** RegularExpression Id. */
	int RPARAM = 23;
	/** RegularExpression Id. */
	int LBLOCK = 24;
	/** RegularExpression Id. */
	int RBLOCK = 25;
	/** RegularExpression Id. */
	int STRING = 26;
	/** RegularExpression Id. */
	int CONSTANT = 27;
	/** RegularExpression Id. */
	int BOOLEAN = 28;
	/** RegularExpression Id. */
	int NATURAL = 29;
	/** RegularExpression Id. */
	int ID = 30;
	/** RegularExpression Id. */
	int DIGIT = 31;
	/** RegularExpression Id. */
	int ZDIGIT = 32;
	/** RegularExpression Id. */
	int LETTER = 33;

	/** Lexical state. */
	int DEFAULT = 0;
	/** Lexical state. */
	int IN_JAVA_DOC_COMMENT = 1;
	/** Lexical state. */
	int IN_MULTI_LINE_COMMENT = 2;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"", "\"\\f\"", "<SINGLE_LINE_COMMENT>", "<token of kind 7>", "\"/*\"", "\"*/\"", "\"*/\"", "<token of kind 11>", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"=\"", "\"!\"", "\">\"", "\"<\"", "\".\"", "\",\"", "\"(\"", "\")\"", "\"{\"", "\"}\"", "<STRING>", "<CONSTANT>", "<BOOLEAN>", "<NATURAL>", "<ID>", "<DIGIT>", "<ZDIGIT>", "<LETTER>", };

}
